<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cours;
use AppBundle\Entity\User;
//use AppBundle\Entity\Niveau;
//use AppBundle\Entity\Salle;
use Doctrine\ORM\EntityRepository;

/**
 * NiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionCoursRepository extends EntityRepository
{
    /**
     * Finds inscriptionCours by user.
     *
     * @param User $user
     *
     * @return \AppBundle\Entity\Cours[]
     */
    public function findByUser(User $user)
    {
        $qb = $this->createQueryBuilder('i');

        return $qb
            ->where($qb->expr()->eq('i.user', ':user'))
            ->getQuery()
            ->setParameter('user', $user)
            ->getResult();
    }

    /**
     * Finds inscriptionCours by cours.
     *
     * @param Cours $cours
     *
     * @return \AppBundle\Entity\User[]
     */
    public function findByCours(Cours $cours)
    {
        $qb = $this->createQueryBuilder('i');

        return $qb
            ->where($qb->expr()->eq('i.cours', ':cours'))
            ->getQuery()
            ->setParameter('cours', $cours)
            ->getResult();
    }
}
