<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeDanseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDanseRepository extends EntityRepository
{
    /**
    * Finds typeDanse by styleDanse.
    *
    * @param StyleDanse $styleDanse
    *
    * @return \AppBundle\Entity\TypeDanse[]
    */
    public function findByStyleDanse(StyleDanse $styleDanse)
    {
        $qb = $this->createQueryBuilder('t');

        return $qb
            ->where($qb->expr()->eq('t.styleDanse', ':styleDanse'))
            ->getQuery()
            ->setParameter('styleDanse', $styleDanse)
            ->getResult();
    }

    /**
     * Finds typeDanse by user.
     *
     * @param User $user
     *
     * @return \AppBundle\Entity\TypeDanse[]
     */
    public function findByUser(User $user)
    {
        $qb = $this->createQueryBuilder('t');

        return $qb
            ->where($qb->expr()->eq('t.user', ':user'))
            ->getQuery()
            ->setParameter('user', $user)
            ->getResult();
    }

    /* public function findOneByNomAndPrenom(User $nom, $prenom)
    {
        $qb = $this->createQueryBuilder('t');

        return $qb
            ->where($qb->expr()->eq('t.nom', ':nom'))
            ->andWhere($qb->expr()->eq('t.prenom', ':prenom'))
            ->getQuery()
            ->setParameters([
                'nom'        => $nom,
                'prenom'     => $prenom,
            ])
            //->getResult();
            ->getOneOrNullResult();
    }*/
}
