
security:
    access_denied_url: /
    role_hierarchy:
        ROLE_RESPONSABLE: [ROLE_ADMIN, ROLE_REFERENT]
        ROLE_REFERENT: ROLE_DANSEUR

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                login_path:
            remember_me:
                key: $secret$
                lifetime: 3000000
                path: /
            logout:       true
            anonymous:    true


    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin(/.*)*$, role: ROLE_RESPONSABLE }
            - { path: ^/evenement/add$, role: ROLE_REFERENT }
            - { path: ^/evenement/edit/\d+$, role: ROLE_REFERENT }
            - { path: ^/evenement/delete/\d+$, role: ROLE_REFERENT }
