app_typeDanse:
    resource: typedanse.yml
    prefix:   /typedanse

admin_index:
    path: /
    defaults: { _controller: AppBundle:Admin:index }

admin_promote:
    path: /promote/{username}
    defaults: { _controller: AppBundle:Admin:promote }
    methods: GET

admin_demote:
    path: /demote/{username}
    defaults: { _controller: AppBundle:Admin:demote }
    methods: GET

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:Admin:delete }
    methods:  DELETE


