app_cours_liste:
    path: /liste
    defaults: { _controller: AppBundle:Cours:liste }

app_cours_add:
    path: /create
    defaults: { _controller: AppBundle:Cours:add }

app_old_cours:
    path: /
    defaults: { _controller: AppBundle:Cours:old }