app_agenda_index:
    path: /
    defaults: { _controller: AppBundle:Evenement:index}
    methods: GET

app_agenda_add:
    path: /new
    defaults: { _controller: AppBundle:Evenement:new}
    methods: [GET, POST]