app_inscriptionCours_index:
    path:   /{id}
    defaults: { _controller: AppBundle:InscriptionCours:index }
    methods:  GET
    requirements:
        id: \d+


app_inscriptionCours_add:
    path: /add/{id}
    defaults: { _controller: AppBundle:InscriptionCours:add }
    requirements:
        id: \d+


app_inscriptionCours_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:InscriptionCours:delete" }



