app_inscriptioncours_add:
    path: /add
    defaults: { _controller: AppBundle:IncriptionCours:add }
app_inscriptioncours_cancel:
    path: /cancel
    defaults: { _controller: AppBundle:IncriptionCours:cancel }