app_typeDanse_index:
    path: /
    defaults: { _controller: AppBundle:TypeDanse:index}
    methods:  GET
    requirements:
        id: \d+

app_typeDanse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:TypeDanse:show" }
    methods:  GET
    requirements:
        id: \d+

app_admin_typeDanse_new:
    path:     /new
    defaults: { _controller: "AppBundle:TypeDanse:new" }
    methods:  [GET, POST]
    requirements:
        id: \d+

app_admin_typeDanse_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:TypeDanse:edit" }
    methods:  [GET, POST]
    requirements:
        id: \d+

app_admin_typeDanse_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:TypeDanse:delete" }
    methods:  DELETE
    requirements:
        id: \d+