app_admin_typeDanse_index:
    path:     /
    defaults: { _controller: "AppBundle:Admin/typeDanse:index" }
    methods:  GET

app_admin_typeDanse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Admin/typeDanse:show" }
    methods:  GET

app_admin_typeDanse_new:
    path:     /new
    defaults: { _controller: "AppBundle:Admin/typeDanse:new" }
    methods:  [GET, POST]

app_admin_typeDanse_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Admin/typeDanse:edit" }
    methods:  [GET, POST]

app_admin_typeDanse_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Admin/typeDanse:delete" }
    methods:  DELETE
