app_home:
    path: /
    defaults: { _controller: AppBundle:Accueil:home }

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin


#app_avis:
#    resource: "@AppBundle/Resources/config/routing/avis.yml"
#    prefix: /avis

app_typeDanse:
    resource: routing/typedanse.yml
    prefix: /typedanse

app_styledanse:
    resource: "routing/styledance.yml"
    prefix: /styledanse



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


