AppBundle\Entity\Avis:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\AvisRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        commentaire:
            type: text

    manyToOne:
        cours:
            targetEntity: BlogBundle\Entity\Cours
            inversedBy: avis
            joinColumn:
                name: cours_id
                referencedColumnName: id
                nullabe: false
#    oneToMany:
#        user:
#            targetEntity: AppBundle\Entity\User
#            mappedBy: avis
    lifecycleCallbacks: {  }
