AppBundle\Entity\Avis:
    type: entity
    table: avis
    repositoryClass: AppBundle\Repository\AvisRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        commentaire:
            type: text

        slug:
            type: string

    manyToOne:
        cours:
            targetEntity: AppBundle\Entity\Cours
            inversedBy: avis
            joinColumn:
                name: cours_id
                referencedColumnName: id
                onDelete: RESTRICT
                nullabe: true

        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: RESTRICT


    lifecycleCallbacks: {  }
