AppBundle\Entity\Cours:
    type: entity
    table: cours
    repositoryClass: AppBundle\Repository\CoursRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateCours:
            type: datetime
        heureDebut:
            type: time
        heureFin:
            type: time
        nombreDanseursMax:
            type: integer

    manyToOne:
        typeDanse:
            targetEntity: AppBundle\Entity\TypeDanse
            joinColumn:
                name: typeDanse_id
                referencedComlumnName: id
                onDelete: RESTRICT


        niveau:
            targetEntity: AppBundle\Entity\Niveau
            joinColumn:
                name: niveau_id
                referencedComlumnName: id
                onDelete: RESTRICT

        salle:
            targetEntity: AppBundle\Entity\Salle
            joinColumn:
                name: salle_id
                referencedComlumnName: id
                onDelete: RESTRICT


        evenement:
            targetEntity: AppBundle\Entity\Evenement
            joinColumn:
                name: evenement_id
                referencedComlumnName: id
                onDelete: RESTRICT

        referent:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: referent
                referencedComlumnName: id
                onDelete: RESTRICT

    oneToMany:
        avis:
            targetEntity: AppBundle\Entity\Avis
            mappedBy: cours
#            cascade: [all]

    manyToMany:
        danseurs:
            targetEntity:   AppBundle\Entity\User
            inversedBy: cours
            joinTable:
                name: cours_danseurs
                joinColumns:
                    cours_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id

        animateurs:
            targetEntity:   AppBundle\Entity\User
            inversedBy: coursAnimes
            joinTable:
                name: animateur
                joinColumns:
                    cours_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }