AppBundle\Entity\Niveau:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\NiveauRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
