AppBundle\Entity\Salle:
    type: entity
    table: salle
    repositoryClass: AppBundle\Repository\SalleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: integer
            unique: true
    lifecycleCallbacks: {  }
