AppBundle\Entity\StyleDanse:
    type: entity
    table: styledanse
    repositoryClass: AppBundle\Repository\StyleDanseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true

        description:
            type: text
            unique: false

    manyToMany:
        typeDanses:
            targetEntity:   AppBundle\Entity\TypeDanse
            inversedBy: styleDanses
            joinTable:
                name: styleDanse_typeDanse
                joinColumns:
                    styleDanse_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    typeDanse_id:
                        referencedColumnName: id


    lifecycleCallbacks: {  }
