AppBundle\Entity\TypeDanse:
    type: entity
    table: typedanse
    repositoryClass: AppBundle\Repository\TypeDanseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
            
        description:
            type: text
            unique: false
            nullable: true

    manyToMany:
        styleDanses:
            targetEntity: AppBundle\Entity\StyleDanse
            mappedBy: typeDanses

<<<<<<< HEAD
=======
        users:
            targetEntity: AppBundle\Entity\User
            mappedBy: typedanse

>>>>>>> d2ffb03f493b552f0684e36d0246ab3c78771737
    lifecycleCallbacks: {  }
