AppBundle\Entity\TypeDanse:
    type: entity
    table: typeDanse
    repositoryClass: AppBundle\Repository\TypeDanseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true

    manyToMany:
        styleDanses:
            targetEntity: AppBundle\Entity\StyleDanse
            mappedBy: TypeDanses

    lifecycleCallbacks: {  }
