AppBundle\Entity\TypeDanse:
    type: entity
    table: typedanse
    repositoryClass: AppBundle\Repository\TypeDanseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
        description:
            type: text
            nullable: true

        description:
            type: text
            unique: false

    manyToMany:
        styleDanses:
            targetEntity: AppBundle\Entity\StyleDanse
            mappedBy: typeDanses



        users:
            targetEntity:   AppBundle\Entity\User
            inversedBy: typeDanses
            joinTable:
                name: typedanse_user
                joinColumns:
                    typeDanse_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    animateurPotentiel_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
