AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 56
            nullable: true
        prenom:
            type: string
            length: 56
            nullable: true
        sexe:
            type: string
            length: 56
            nullable: true


    manyToMany:
        cours:
            targetEntity: AppBundle\Entity\Cours
            mappedBy: danseurs
#            mappedBy: animateurs

        typeDanses:
            targetEntity:   AppBundle\Entity\TypeDanse
            inversedBy: users
            joinTable:
                name: typedanse_user
                joinColumns:
                    animateurPotentiel_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    typeDanse_id:
                        referencedColumnName: id

        coursAnimes:
            targetEntity: AppBundle\Entity\Cours
            mappedBy: animateurs


    lifecycleCallbacks: {  }
