AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 56
            nullable: false
        prenom:
            type: string
            length: 56
            nullable: false
        sex:
            type: string
            length: 56
            nullable: false
#        statut:
#            type: string
#            length: 56
#            nullable: false
#            options:
#                default: "danseur"

    oneToMany:
        avis:
            targetEntity: AppBundle\Entity\Avis
            mappedBy: user
    manyToOne:
        statut:
            targetEntity: AppBundle\Entity\Statut
            joinColumn:
                name: statut_id
                referencedComlumnName: id
                onDelete: RESTRICT

    lifecycleCallbacks: {  }
#    manyToOne:
#            statut:
#                targetEntity: AppBundle\Entity\Statut
#                joinColum:
#                    name: statut_id
#                    referencedColumnName: id
#                    nullable: false
#                onDelete: RESTRICT