AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
        cours:
            targetEntity:   AppBundle\Entity\Cours
            inversedBy: danseurs
            joinTable:
                name: cours_danseurs
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    cours_id:
                        referencedColumnName: id

        typeDanses:
            targetEntity: AppBundle\Entity\TypeDanse
            mappedBy: users

        coursAnimes:
            targetEntity: AppBundle\Entity\Cours
            mappedBy: animateurs


    lifecycleCallbacks: {  }


