AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
            statut:
                targetEntity: AppBundle\Entity\Staatut
                joinColum:
                    name: statut_id
                    referencedColumnName: id
                    nullable: false
                onDelete: RESTRICT